INSERT INTO brand_model (brand_name, brand_model) 
	VALUES ("BAJAJ", "4s Champion"),
	("BAJAJ", "Avenger"),
	("BAJAJ", "Avenger 220 DTS-i"),
	("BAJAJ", "Avenger Cruise 150"),
	("BAJAJ", "Avenger Cruise 220 "),
	("BAJAJ", "Avenger Street 150"),
	("BAJAJ", "Avenger Street 220"),
	("BAJAJ", "CT100"),
	("BAJAJ", "Discover 100"),
	("BAJAJ", "Discover 100 M"),
	("BAJAJ", "Discover 100 T"),
	("BAJAJ", "Discover 125"),
	("BAJAJ", "Discover 125 M"),
	("BAJAJ", "Discover 125T"),
	("BAJAJ", "Discover 150F"),
	("BAJAJ", "Discover 150S"),
	("BAJAJ", "Platina"),
	("BAJAJ", "Platina 100CC"),
	("BAJAJ", "Platina 125 DTS-Si"),
	("BAJAJ", "Pulsar 135 LS"),
	("BAJAJ", "Pulsar 150 DTS- i"),
	("BAJAJ", "Pulsar 180 DTS- i"),
	("BAJAJ", "Pulsar 200NS"),
	("BAJAJ", "Pulsar 220 DTS- Fi"),
	("BAJAJ", "Pulsar 220 DTS- i"),
	("BAJAJ", "Pulsar 220F"),
	("BAJAJ", "Pulsar AS150"),
	("BAJAJ", "Pulsar AS200"),
	("BAJAJ", "Pulsar RS200"),
	("BAJAJ", "V15"),
	("BAJAJ", "XCD 125 DTS-Si"),
	("BAJAJ", "XCD 135 DTS-Si");
	
	
	INSERT INTO brand_model (brand_name, brand_model) 
	VALUES("HERO", "Achiever"),
	("HERO", "Ambition 133"),
	("HERO", "Ambition 135"),
	("HERO", "CBZ"),
	("HERO", "CBZ Xtreme"),
	("HERO", "CBZ Star"),
	("HERO", "CD 100"),
	("HERO", "CD 100 SS"),
	("HERO", "CD Dawn"),
	("HERO", "CD Deluxe"),
	("HERO", "Duet"),
	("HERO", "Duet LX"),
	("HERO", "Duet VX"),
	("HERO", "Glamour"),
	("HERO", "Glamour FI"),
	("HERO", "HF Dawn"),
	("HERO", "HF Deluxe"),
	("HERO", "HF Deluxe Eco"),
	("HERO", "Hunk"),
	("HERO", "Ignitor"),
	("HERO", "Impulse"),
	("HERO", "Karizma 2014"),
	("HERO", "Karizma ZMR 2014"),
	("HERO", "Maestro"),
	("HERO", "Maestro Edge"),
	("HERO", "Passion Plus"),
	("HERO", "Passion PRO"),
	("HERO", "Passion X Pro"),
	("HERO", "Pleasure"),
	("HERO", "Pleasure 2014"),
	("HERO", "Sleek"),
	("HERO", "Splendor iSmart"),
	("HERO", "Splendor NXG"),
	("HERO", "Splendor Plus"),
	("HERO", "Splendor PRO"),
	("HERO", "Super Splendor"),
	("HERO", "Xtreme");
	
	INSERT INTO brand_model (brand_name, brand_model) 
	VALUES("HONDA", "Activa"),
	("HONDA", "Activa 125"),
	("HONDA", "Activa-i"),
	("HONDA", "Aviator"),
	("HONDA", "CB Shine"),
	("HONDA", "CB Trigger"),
	("HONDA", "CB Twister"),
	("HONDA", "CB Unicorn"),
	("HONDA", "CB1000R"),
	("HONDA", "CBR1000RR Fireblade"),
	("HONDA", "CBR150 R"),
	("HONDA", "CBR250R"),
	("HONDA", "CD 110 Dream"),
	("HONDA", "Dio"),
	("HONDA", "Dream Neo"),
	("HONDA", "Dream Yuga"),
	("HONDA", "Hornet"),
	("HONDA", "Kinetic"),
	("HONDA", "Livo"),
	("HONDA", "Navi"),
	("HONDA", "Stunner"),
	("HONDA", "VFR"),
	("HONDA", "VT");
	
	INSERT INTO brand_model (brand_name,brand_model) 
	VALUES("MAHINDRA", "Centuro Disc Brake"),
	("MAHINDRA", "Centuro NXT"),
	("MAHINDRA", "Centuro Rockstar"),
	("MAHINDRA", "Centuro Rockstar Kick Alloy"),
	("MAHINDRA", "Centuro XT"),
	("MAHINDRA", "Duro DZ"),
	("MAHINDRA", "Gusto"),
	("MAHINDRA", "Mojo"),
	("MAHINDRA", "Pantero"),
	("MAHINDRA", "Rodeo UZO 125");
	
	INSERT INTO brand_model (brand_name,brand_model) 
	VALUES("ROYAL_ENFIELD", "Battle Green"),
	("ROYAL_ENFIELD", "Bullet 350"),
	("ROYAL_ENFIELD", "Bullet 500"),
	("ROYAL_ENFIELD", "Bullet Electra"),
	("ROYAL_ENFIELD", "Classic 350"),
	("ROYAL_ENFIELD", "Classic 500"),
	("ROYAL_ENFIELD", "Classic Chrome"),
	("ROYAL_ENFIELD", "Continental GT"),
	("ROYAL_ENFIELD", "Desert Storm"),
	("ROYAL_ENFIELD", "Himalayan"),
	("ROYAL_ENFIELD", "Thunderbird 350"),
	("ROYAL_ENFIELD", "Thunderbird 500");
	
	INSERT INTO brand_model (brand_name,brand_model) 
	VALUES("TVS", "Apache RTR"),
	("TVS", "Apache RTR 160 New Design"),
	("TVS", "Apache RTR 160 New Design R/D"),
	("TVS", "Apache RTR 160 Old Design"),
	("TVS", "Apache RTR 160 Old Design R/D"),
	("TVS", "Apache RTR 180 New"),
	("TVS", "Apache RTR 180 Old Design"),
	("TVS", "Apache RTR 200"),
	("TVS", "Apache RTR 200 4v"),
	("TVS", "Apache RTR ABS 180"),
	("TVS", "Fiero"),
	("TVS", "Jupiter"),
	("TVS", "Max 4R"),
	("TVS", "Phoenix 125 Alpine Series"),
	("TVS", "Phoenix 125 Disc"),
	("TVS", "Phoenix 125 Drum"),
	("TVS", "Scooty Pep+"),
	("TVS", "Scooty Pep+ Babelicious"),
	("TVS", "Scooty Pep+ Fashion"),
	("TVS", "Scooty Streak"),
	("TVS", "Scooty Streak Fashion"),
	("TVS", "Scooty Zest"),
	("TVS", "Sport CTVi Es"),
	("TVS", "Star City +"),
	("TVS", "Star City Mag Ref"),
	("TVS", "Victor 2016"),
	("TVS", "Victor GLX"),
	("TVS", "Wego Basic"),
	("TVS", "Wego Disc"),
	("TVS", "Wego UPG"),
	("TVS", "XL Super"),
	("TVS", "XL Super Heavy Duty");
	
	INSERT INTO brand_model (brand_name,brand_model) 
	VALUES("SUZUKI", "Access 125"),
	("SUZUKI", "Bandit 1250SA"),
	("SUZUKI", "Gixxer"),
	("SUZUKI", "Gixxer SF"),
	("SUZUKI", "GS 15 R"),
	("SUZUKI", "GSX - R 1000"),
	("SUZUKI", "GSX - S 1000"),
	("SUZUKI", "GSX - S 1000F "),
	("SUZUKI", "Hayabusa"),
	("SUZUKI", "Hayate"),
	("SUZUKI", "Intruder 800"),
	("SUZUKI", "Intruder M1800R"),
	("SUZUKI", "Let's"),
	("SUZUKI", "Sling Shot Plus"),
	("SUZUKI", "Swish 125"),
	("SUZUKI", "V - Storm");
	
	INSERT INTO brand_model (brand_name,brand_model) 
	VALUES("VESPA", "ELEGANT"),
	("VESPA", "ELEGANT (NEW)"),
	("VESPA", "LX 125"),
	("VESPA", "LX 150"),
	("VESPA", "S"),
	("VESPA", "S"),
	("VESPA", "SXL 125"),
	("VESPA", "SXL 150"),
	("VESPA", "VX 125"),
	("VESPA", "VX 150"),
	("VESPA", "VX SPL EDITION"),
	("VESPA", "VXL 125"),
	("VESPA", "VXL 150");
	
	INSERT INTO brand_model (brand_name,brand_model) 
	VALUES("YAMAHA", " YBR 125"),
	("YAMAHA", "Alpha"),
	("YAMAHA", "Crux"),
	("YAMAHA", "Fasino"),
	("YAMAHA", "Fazer"),
	("YAMAHA", "FZ S"),
	("YAMAHA", "FZ S V 2.0"),
	("YAMAHA", "FZ V 2.0"),
	("YAMAHA", "FZ1"),
	("YAMAHA", "FZ16"),
	("YAMAHA", "Ray"),
	("YAMAHA", "Ray ZR"),
	("YAMAHA", "Ray-Z"),
	("YAMAHA", "RX 100"),
	("YAMAHA", "RX 135"),
	("YAMAHA", "Saluto"),
	("YAMAHA", "SS"),
	("YAMAHA", "SZ-RR"),
	("YAMAHA", "SZ-S"),
	("YAMAHA", "Vmax"),
	("YAMAHA", "YBR 110"),
	("YAMAHA", "YZF R1"),
	("YAMAHA", "YZF R15");
	
	INSERT INTO brand_model (brand_name,brand_model) 
	VALUES("KTM", "Duke 200"),
	("KTM", "Duke 390"),
	("KTM", "RC 200"),
	("KTM", "RC 390");